# Новостной ресурс.

- Автор: Бышин М.И. (hh.ru/resume/3a27e4d7ff0ef40ab90039ed1f6f445a567078)

## Задание № 1
##### Задача. Необходимо нормализовать базу данных, приведя все записи в предоставленном датасете к единому формату даты DD-MM-YYYY, с соблюдением порядка записей.
Требования:
1. Обработка данных:
- Загрузите предоставленный датасет, содержащий даты в различных форматах.
- Приведите все даты к единому формату DD-MM-YYYY.
- Если в записи отсутствует год, заполните его значением 1900.
2. Сохранение порядка:
- Обеспечьте, чтобы порядок записей в датасете не изменялся, т.е. каждая дата оставалась на своем исходном индексе.
3.	Технические требования:
- Используйте язык программирования Python.
- Используйте библиотеку pandas для обработки и нормализации данных.
- Реализуйте обработку возможных ошибок, связанных с некорректными форматами дат.
4.	Дополнительные требования (по желанию):
- Напишите тесты для проверки корректности нормализации.
- Создайте отчет о выполненной нормализации с указанием количества исправленных записей и примеров.

Итог:
- Исходный код программы на языке Python.
- Пример нормализованного датасета (в формате CSV).
- Краткое описание этапов нормализации и возможных сложностей, с которыми вы столкнулись.

In [ ]:
# Импортируем библиотеки
import pandas as pd

# Загружаем библиотеки для визуализации данных
import matplotlib.pyplot as plt
import seaborn as sns

**Данные:**

- Датасет переименован в `data`.

In [ ]:
# Выгружаем данные
dates = pd.read_csv('C:\\Users\\Downloads\\data.csv') # Не забудьте поменять ссылку на свою!

In [ ]:
# Знакомство
dates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 1 columns):
 #   Column  Dtype
---  ------  -----
 0   date    object
dtypes: object(1)
memory usage: 15.3+ MB

In [ ]:
# Осмотр
dates.head(10)

         date
0   20.9.1901
1    6.5.1999
2   31.7.1988
3    5.8.1982
4   18.1.1992
5   29.7.1984
6   22.2.2005
7         NaN
8  23.10.1999
9         9.7

### Решение V1 (грузит ядро на 146 секунд)

In [ ]:
# Пишем функцию нормализации дат
def normalize_date(date_str):
    if pd.isna(date_str): # Проверяем пропущенные значения
        return pd.NA # Возвращаем специальное значение для пропущенных данных

    parts = str(date_str).split('.')  # Делим строку даты по точкам
    parts_count = len(parts)  # Считаем количество полученных часте

    # Обрабатываем день
    day = parts[0].zfill(2) if parts_count >= 1 else '01' # Добавляем ноль если нужно

    # Обрабатываем месяц
    month = parts[1].zfill(2) if parts_count >= 2 else '01' # Аналогично добавляем ноль

    # Обрабатываем год
    if parts_count >= 3: # Если год указан
        year = parts[2] if len(parts[2]) == 4 else '1900' # Проверяем формат года
    else: # Если год не указан
        year = '1900' # Устанавливаем год по умолчанию

    # Формируем нормализованную дату
    normalized = f"{day}.{month}.{year}"

    # Проверяем валидность даты(существует ли такая дата)
    try:
        pd.to_datetime(normalized, format='%d.%m.%Y') # Пробуем преобразовать в datetime
        return normalized
    except:
        return pd.NA # Если дата невалидна - возвращаем пропущенное значение

In [ ]:
# Создаем копию исходных данных для будущего отчета
original_dates = dates.copy()

# Применяем нормализацию
dates['date'] = dates['date'].apply(normalize_date) # Ждём 146 сек

In [ ]:
# Проверяем рузультат визуально
dates.head(10)

         date
0  20.09.1901
1  06.05.1999
2  31.07.1988
3  05.08.1982
4  18.01.1992
5  29.07.1984
6  22.02.2005
7        <NA>
8  23.10.1999
9  09.07.1900

In [ ]:
# Создаем отчет с результатами обработки
report_data = {
    'total_records': len(dates), # Общее количество записей
    'corrected_records': (original_dates['date'] != dates['date']).sum(), # Число измененных записей
    'null_values_before': original_dates['date'].isna().sum(), # Пропуски до обработки
    'null_values_after': dates['date'].isna().sum(), # Пропуски после обработки
    'examples': pd.concat([original_dates.head(10), dates.head(10)], axis=1)  # Примеры первых 10 строк
}

# Выводим отчет
print("Отчет о нормализации дат:")
print(f"Всего записей: {report_data['total_records']}")
print(f"Исправлено записей: {report_data['corrected_records']}")
print(f"Пустых значений до обработки: {report_data['null_values_before']}")
print(f"Пустых значений после обработки: {report_data['null_values_after']}")
print("\nПримеры преобразований:")
for i in range(10):
    orig = original_dates['date'].iloc[i] if i < len(original_dates) else ''
    norm = dates['date'].iloc[i] if i < len(dates) else ''
    print(f"{orig} -> {norm}")

Отчет о нормализации дат:
Всего записей: 2000000
Исправлено записей: 1769726
Пустых значений до обработки: 291132
Пустых значений после обработки: 291414

Примеры преобразований:
20.9.1901 -> 20.09.1901
6.5.1999 -> 06.05.1999
31.7.1988 -> 31.07.1988
5.8.1982 -> 05.08.1982
18.1.1992 -> 18.01.1992
29.7.1984 -> 29.07.1984
22.2.2005 -> 22.02.2005
nan -> <NA>
23.10.1999 -> 23.10.1999
9.7 -> 09.07.1900

In [ ]:
# Сохраняем нормализованный файл
dates.to_csv('C:\\Users\\Max Man\\Downloads\\normalized_dates.csv', index=False)

### Решение V2 при помощи NumPy(работает намного быстрее!)

In [ ]:
import numpy as np

# Создаем копию исходного DataFrame для отчета
original_dates = dates.copy()

# Функция для нормализации дат с использованием только pandas
def normalize_dates_pandas(df):
    # Разделяем дату на компоненты
    split_date = df['date'].str.split('.', expand=True)

    # Заполняем компоненты даты
    day = split_date[0].fillna('01').str.zfill(2)
    month = split_date[1].fillna('01').str.zfill(2)
    year = split_date[2].fillna('1900')

    # Исправляем годы с неправильным форматом
    year = np.where(year.str.len() != 4, '1900', year)

    # Собираем дату обратно
    normalized = day + '.' + month + '.' + year

    # Проверяем валидность даты
    valid_mask = pd.to_datetime(normalized, format='%d.%m.%Y', errors='coerce').notna()
    df['normalized_date'] = np.where(valid_mask, normalized, np.nan)

    return df

# Применяем нормализацию
dates = normalize_dates_pandas(dates)

# Заменяем исходный столбец и удаляем временный
dates['date'] = dates['normalized_date']
dates.drop(columns=['normalized_date'], inplace=True)

# Создаем отчет
report = pd.DataFrame({
    'original': original_dates['date'],
    'normalized': dates['date']
})

# Вычисляем статистику
stats = {
    'total_records': len(dates),
    'corrected_records': (report['original'] != report['normalized']).sum(),
    'null_values_before': report['original'].isna().sum(),
    'null_values_after': report['normalized'].isna().sum(),
    'examples': report.head(10).to_dict('records')
}

# Выводим отчет
print("Отчет о нормализации дат:")
print(f"Всего записей: {stats['total_records']}")
print(f"Исправлено записей: {stats['corrected_records']}")
print(f"Пустых значений до обработки: {stats['null_values_before']}")
print(f"Пустых значений после обработки: {stats['null_values_after']}")
print("\nПримеры преобразований:")
for example in stats['examples']:
    print(f"{example['original']} -> {example['normalized']}")

Отчет о нормализации дат:
Всего записей: 2000000
Исправлено записей: 291414
Пустых значений до обработки: 291414
Пустых значений после обработки: 0

Примеры преобразований:
20.09.1901 -> 20.09.1901
06.05.1999 -> 06.05.1999
31.07.1988 -> 31.07.1988
05.08.1982 -> 05.08.1982
18.01.1992 -> 18.01.1992
29.07.1984 -> 29.07.1984
22.02.2005 -> 22.02.2005
None -> 01.01.1900
23.10.1999 -> 23.10.1999
09.07.1900 -> 09.07.1900

### Задание 1 итог:
- Исходный код программы на языке Python: выше.
- Пример нормализованного датасета (в формате CSV): прикреплю файл под названием `normalized_dates.csv`.
- Краткое описание этапов нормализации и возможных сложностей, с которыми вы столкнулись: подробно описал каждый шаг в комментарии под `#` справа от строчек кода. Сложностей не заметил, разве, что с библиотекой nampy код работет намного быстрее.

## Задание № 2
##### Задача. Напишите программу для сбора и анализа данных из открытых источников новостей, удовлетворяющую следующим минимальным требованиям:

1.	Сбор данных:
- Используйте RSS-ленту для сбора новостей о политических партиях или деятелях.
- Используйте официальное API новостного агрегатора для сбора новостей о тех же политических партиях или деятелях.
2.	Анализ данных:
- Программа должна извлекать статьи, содержащие упоминания конкретных политических партий или деятелей.
- Анализируйте частоту упоминаний и контекст в различных медиа (используемых источниках).
- Стройте временные ряды для отслеживания динамических изменений в медийной активности.
- Сделайте выводы о корреляции медийной активности с политическими событиями.
3.	Технические требования:
- Используйте язык программирования Python.
- Для работы с RSS-лентами и API новостных агрегаторов используйте соответствующие библиотеки (например, feedparser для RSS и библиотеки для работы с API конкретных новостных агрегаторов).
- Реализуйте возможность сохранения данных для дальнейшего анализа.
- Включите комментарии к коду для объяснения основных этапов и принятых решений.
4.	Дополнительные требования (по желанию):
- Реализуйте интерактивную визуализацию результатов анализа (например, с использованием библиотеки matplotlib).
- Обеспечьте возможность конфигурации и расширения функциональности программы.

Дополнительная информация:
- В качестве политических партий или деятелей могут быть выбраны произвольные имена для целей тестирования.
- Программа должна быть написана таким образом, чтобы она могла работать на продолжительное время, обеспечивая регулярное обновление данных и анализ.

Итог:
- Исходный код программы на языке Python.
- Краткое описание основных шагов и решений, принятых в процессе разработки.
- Примеры визуализаций (при наличии).

### Решение

**Ключевые моменты реализации:**

- Модульность:
    - Код разделен на два основных класса: NewsCollector (сбор данных) и NewsAnalyzer (анализ данных)
    - Каждый класс отвечает за свою часть функциональности

- Обработка ошибок:
    - Все критические операции обернуты в try-except
    - Программа продолжает работу даже при ошибках в отдельных источниках

- Гибкость:
    - Конфигурация вынесена в отдельный словарь CONFIG
    - Легко добавить новые источники или политические субъекты

- Сохранение данных:
    - Сырые данные сохраняются в JSON
    - Обработанные данные - в CSV
    - Графики - в PNG файлы

- Визуализация:
    - Используется matplotlib для создания понятных графиков
    - Два типа визуализаций: динамика и распределение по источникам

- Периодичность обновления:
    - Программа работает в бесконечном цикле с настраиваемым интервалом
    - Можно остановить сочетанием клавиш Ctrl+C

In [ ]:
# Импорт необходимых библиотек
!pip install feedparser requests pandas matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: feedparser in c:\users\max man\appdata\roaming\python\python313\site-packages (6.0.11)
Requirement already satisfied: requests in c:\users\max man\appdata\roaming\python\python313\site-packages (2.32.3)
Requirement already satisfied: pandas in c:\users\max man\appdata\roaming\python\python313\site-packages (2.2.3)
Requirement already satisfied: matplotlib in c:\users\max man\appdata\roaming\python\python313\site-packages (3.10.3)
Requirement already satisfied: sgmllib3k in c:\users\max man\appdata\roaming\python\python313\site-packages (from feedparser) (1.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\max man\appdata\roaming\python\python313\site-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\max man\appdata\roaming\python\python313\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\max man\appdata\roaming\python\python313\site-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\max man\appdata\roaming\python\python313\site-packages (from requests) (2025.4.26)
Requirement already satisfied: numpy>=1.26.0 in c:\users\max man\appdata\roaming\python\python313\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\max man\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\max man\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\max man\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\max man\appdata\roaming\python\python313\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\max man\appdata\roaming\python\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\max man\appdata\roaming\python\python313\site-packages (from matplotlib) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\max man\appdata\roaming\python\python313\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\max man\appdata\roaming\python\python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\max man\appdata\roaming\python\python313\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\max man\appdata\roaming\python\python313\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: six>=1.5 in c:\users\max man\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# Запуск программы
# python news_analyzer.py

In [ ]:
# Импорт необходимых библиотек
import feedparser  # Для парсинга RSS-лент
import requests  # Для работы с HTTP-запросами (API новостей)
import pandas as pd  # Для работы с табличными данными
from datetime import datetime  # Для работы с датами
import matplotlib.pyplot as plt  # Для визуализации данных
import json  # Для работы с JSON-форматом
import time  # Для работы с временными задержками
from collections import defaultdict  # Для удобной работы со словарями
import os  # Для работы с файловой системой

In [ ]:
# Конфиг программы в виде словаря
CONFIG = {
    # Создаём список политических субъектов для мониторинга
    "political_entities": ["Путин", "Зеленский", "Байден", "Трамп", "Единая Россия", "КПРФ", "США", "Россия", "Украина"],
    # Создаём список RSS-лент для анализа
    "rss_feeds": [
        "https://lenta.ru/rss/news",
        "https://www.vedomosti.ru/rss/news",
        "https://www.kommersant.ru/RSS/news.xml"
    ],
    # Настройки для NewsAPI
    "newsapi_config": {
        "api_key": "a61bf49cc7f9437a93190a3f0c3b5cba",  # Ключ API
        "sources": "bbc-news,cnn,reuters",  # Источники новостей
        "language": "ru"  # Язык новостей
    },
    # Настройки хранения данных
    "storage": {
        "raw_data": "data/raw_news.json",  # Путь к файлу с сырыми данными
        "processed_data": "data/processed_news.csv",  # Путь к обработанным данным
        "plots": "plots/"  # Директория для графиков
    },
    # Интервал обновления данных в секундах
    "update_interval": 3600
}

class NewsCollector:
    """
    Класс для сбора новостей из RSS-лент и по API.
    Основные функции:
    - fetch_rss_news: сбор новостей из RSS-лент
    - fetch_newsapi_news: сбор новостей через NewsAPI
    - collect_news: основной метод сбора данных
    - save_raw_data: сохранение сырых данных
    """

    def __init__(self, config):
        """Инициализация коллектора с конфигурацией"""
        self.config = config  # Сохраняем конфигурацию
        self.ensure_data_directories()  # Создаем необходимые директории

    def ensure_data_directories(self):
        """Создает необходимые директории для хранения данных, если они не существуют"""
        # os.makedirs создает директории, exist_ok=True предотвращает ошибку если директория уже существует
        os.makedirs(os.path.dirname(self.config["storage"]["raw_data"]), exist_ok=True)
        os.makedirs(self.config["storage"]["plots"], exist_ok=True)

    def fetch_rss_news(self):
        """
        Сбор новостей из RSS-лент.
        Возвращает список новостей, содержащих упоминания политических субъектов.
        """
        news_items = []  # Пкстой список для хранения найденных новостей

        # Перебираем все RSS-ленты из конфигурации
        for rss_url in self.config["rss_feeds"]:
            try:
                # Парсим RSS-ленту
                feed = feedparser.parse(rss_url)

                # Перебираем все записи в RSS-ленте
                for entry in feed.entries:
                    # Создаем словарь с информацией о новости
                    news_item = {
                        "title": entry.get("title", ""),  # Заголовок новости
                        "description": entry.get("description", ""),  # Описание
                        "link": entry.get("link", ""),  # Ссылка на новость
                        "published": entry.get("published", ""),  # Дата публикации
                        "source": "RSS: " + rss_url,  # Источник новости
                        "contains_entities": []  # Список упомянутых политических субъектов
                    }

                    # Проверяем упоминания каждого политического субъекта
                    for entity in self.config["political_entities"]:
                        # Ищем упоминание в заголовке или описании (без учета регистра)
                        if entity.lower() in news_item["title"].lower() or entity.lower() in news_item["description"].lower():
                            news_item["contains_entities"].append(entity)  # Добавляем в список

                    # Если есть упоминания, добавляем новость в результат
                    if news_item["contains_entities"]:
                        news_items.append(news_item)

            except Exception as e:
                # В случае ошибки выводим сообщение и продолжаем работу
                print(f"Ошибка при обработке RSS {rss_url}: {e}")

        return news_items

    def fetch_newsapi_news(self):
        """
        Сбор новостей через NewsAPI.
        Для работы требуется API ключ от newsapi.org.
        """
        news_items = []  # Пустой список для хранения новостей
        api_key = self.config["newsapi_config"]["api_key"]  # Получаем API ключ

        # Проверяем, установлен ли API ключ
        if api_key == "YOUR_API_KEY":
            print("Предупреждение: NewsAPI не будет использоваться, так как не установлен API ключ")
            return news_items  # Возвращаем пустой список если ключ не установлен

        base_url = "https://newsapi.org/v2/everything"  # Базовый URL API

        # Перебираем все политические субъекты
        for entity in self.config["political_entities"]:
            try:
                # Параметры запроса
                params = {
                    "q": entity,  # Поисковый запрос
                    "sources": self.config["newsapi_config"]["sources"],  # Источники
                    "language": self.config["newsapi_config"]["language"],  # Язык
                    "apiKey": api_key  # API ключ
                }

                # Отправляем get-запрос к API
                response = requests.get(base_url, params=params)
                response.raise_for_status()  # Проверяем на ошибки
                data = response.json()  # Парсим JSON-ответ

                # Обрабатываем полученные новости
                for article in data.get("articles", []):
                    # Создаем словарь с информацией о новости
                    news_item = {
                        "title": article.get("title", ""), # Заголовок новости
                        "description": article.get("description", ""), # Описание
                        "link": article.get("url", ""), # Ссылка на новость
                        "published": article.get("publishedAt", ""), # Дата
                        "source": "NewsAPI: " + article.get("source", {}).get("name", ""), # Ичточник
                        "contains_entities": [entity]  # Записываем найденный субъект
                    }
                    news_items.append(news_item)  # Добавляем новость в список

                # Делаем паузу между запросами для соблюдения лимитов NewsAPI
                time.sleep(1)

            except Exception as e:
                # В случае ошибки выводим сообщение и продолжаем работу
                print(f"Ошибка при запросе NewsAPI для '{entity}': {e}")

        return news_items

    def collect_news(self):
        """
        Основной метод сбора новостей из всех источников.
        Объединяет результаты из RSS и API.
        """
        print("Начало сбора новостей...")
        # Получаем новости из RSS
        rss_news = self.fetch_rss_news()
        # Получаем новости из NewsAPI
        api_news = self.fetch_newsapi_news()
        # Объединяем результаты
        all_news = rss_news + api_news

        # Выводим статистику
        print(f"Собрано {len(all_news)} новостей (RSS: {len(rss_news)}, API: {len(api_news)})")
        return all_news

    def save_raw_data(self, news_data):
        """
        Сохраняет сырые данные в JSON файл.
        """
        # Открываем файл для записи
        with open(self.config["storage"]["raw_data"], "w", encoding="utf-8") as f:
            # Записываем данные в JSON с отступами
            json.dump(news_data, f, ensure_ascii=False, indent=2)
        print(f"Сырые данные сохранены в {self.config['storage']['raw_data']}")

class NewsAnalyzer:
    """
    Класс для анализа собранных новостей.
    Основные функции:
    - process_news_data: обработка сырых данных
    - analyze_mentions: анализ частоты упоминаний
    - visualize_results: визуализация результатов
    """

    def __init__(self, config):
        """Инициализация анализатора с конфигурацией"""
        self.config = config  # Сохраняем конфигурацию

    def load_raw_data(self):
        """
        Загружает сырые данные из файла.
        Возвращает список новостей или пустой список при ошибке.
        """
        try:
            # Открываем файл для чтения
            with open(self.config["storage"]["raw_data"], "r", encoding="utf-8") as f:
                return json.load(f)  # Загружаем JSON данные
        except FileNotFoundError:
            print("Файл с сырыми данными не найден")
            return []  # Возвращаем пустой список если файл не найден

    def process_news_data(self, news_data):
        """
        Обрабатывает новостные данные и создает dataframe для анализа.
        Разбирает даты, нормализует структуру данных.
        """
        processed_data = []  # Пустой список для обработанных данных

        # Перебираем все новости
        for news_item in news_data:
            try:
                # Получаем дату публикации
                pub_date = news_item.get("published", "")
                try:
                    # Пробуем разобрать дату в формате ISO (NewsAPI)
                    pub_date = datetime.strptime(pub_date, "%Y-%m-%dT%H:%M:%SZ")
                except:
                    try:
                        # Пробуем разобрать дату в формате RSS
                        pub_date = datetime.strptime(pub_date, "%a, %d %b %Y %H:%M:%S %z")
                    except:
                        # Если не удалось, используем текущую дату
                        pub_date = datetime.now()

                # Для каждого упомянутого субъекта создаем отдельную запись
                for entity in news_item["contains_entities"]:
                    processed_data.append({
                        "date": pub_date.date(),  # Дата без времени
                        "entity": entity,  # Политический субъект
                        "title": news_item["title"],  # Заголовок новости
                        "source": news_item["source"],  # Источник
                        "link": news_item["link"]  # Ссылка
                    })

            except Exception as e:
                # В случае ошибки выводим сообщение и продолжаем
                print(f"Ошибка при обработке новости: {e}")
                continue

        # Создаем dataframe из обработанных данных
        df = pd.DataFrame(processed_data)
        return df

    def analyze_mentions(self, df):
        """
        Анализирует частоту упоминаний по дням и источникам.
        Возвращает два dataframe:
        - daily_mentions: упоминания по дням
        - source_mentions: упоминания по источникам
        """
        if df.empty:
            return None, None  # Возвращаем None если данных нет

        # Группируем по дате и субъекту, считаем количество
        daily_mentions = df.groupby(["date", "entity"]).size().unstack(fill_value=0)

        # Группируем по источнику и субъекту, считаем количество
        source_mentions = df.groupby(["source", "entity"]).size().unstack(fill_value=0)

        return daily_mentions, source_mentions

    def save_processed_data(self, df):
        """
        Сохраняет обработанные данные в CSV файл.
        """
        # Сохраняем dataframe в CSV без индекса
        df.to_csv(self.config["storage"]["processed_data"], index=False, encoding="utf-8")
        print(f"Обработанные данные сохранены в {self.config['storage']['processed_data']}")

    def visualize_results(self, daily_mentions, source_mentions):
        """
        Создает визуализации результатов анализа.
        Генерирует два графика:
        1. Динамика упоминаний по дням
        2. Распределение упоминаний по источникам
        """
        # Проверяем, есть ли данные для визуализации
        if daily_mentions is None or source_mentions is None:
            print("Нет данных для визуализации")
            return

        # Создаем график динамики упоминаний
        plt.figure(figsize=(12, 6))  # Задаем размер графика
        # Рисуем линии для каждого политического субъекта
        for column in daily_mentions.columns:
            plt.plot(daily_mentions.index, daily_mentions[column], label=column)

        # Настраиваем внешний вид графика
        plt.title("Динамика упоминаний политических субъектов")
        plt.xlabel("Дата")
        plt.ylabel("Количество упоминаний")
        plt.legend()  # Добавляем легенду
        plt.grid()  # Добавляем сетку
        plt.xticks(rotation=45)  # Поворачиваем подписи дат
        plt.tight_layout()  # Оптимизируем расположение элементов

        # Сохраняем график в файл
        daily_plot_path = os.path.join(self.config["storage"]["plots"], "daily_mentions.png")
        plt.savefig(daily_plot_path)
        print(f"График динамики сохранен в {daily_plot_path}")
        plt.close()  # Закрываем график для освобождения памяти

        # Создаем график распределения по источникам
        source_mentions.plot(kind="bar", stacked=True, figsize=(12, 6))
        plt.title("Упоминания политических субъектов по источникам")
        plt.xlabel("Источник")
        plt.ylabel("Количество упоминаний")
        plt.xticks(rotation=45)
        plt.tight_layout()

        # Сохраняем второй график
        source_plot_path = os.path.join(self.config["storage"]["plots"], "source_mentions.png")
        plt.savefig(source_plot_path)
        print(f"График по источникам сохранен в {source_plot_path}")
        plt.close() # Закрываем график для освобождения памяти

def main():
    """
    Основная функция программы.
    Организует бесконечный цикл сбора и анализа данных.
    """
    # Инициализация классов
    collector = NewsCollector(CONFIG)  # Создаем сборщик новостей
    analyzer = NewsAnalyzer(CONFIG)  # Создаем анализатор

    try:
        # Бесконечный цикл работы программы
        while True:
            # 1. Сбор данных
            news_data = collector.collect_news()  # Собираем новости
            collector.save_raw_data(news_data)  # Сохраняем сырые данные

            # 2. Анализ данных
            df = analyzer.process_news_data(news_data)  # Обрабатываем данные
            if not df.empty:  # Если есть данные
                analyzer.save_processed_data(df)  # Сохраняем обработанные данные
                # Анализируем упоминания
                daily_mentions, source_mentions = analyzer.analyze_mentions(df)
                # Визуализируем результаты
                analyzer.visualize_results(daily_mentions, source_mentions)

            # 3. Ожидание следующего обновления
            print(f"Ожидание следующего обновления через {CONFIG['update_interval']} секунд...")
            time.sleep(CONFIG["update_interval"])  # Пауза

    except KeyboardInterrupt:
        # Обработка прерывания программы (Ctrl+C)
        print("Программа остановлена пользователем")

if __name__ == "__main__":
    # Точка входа в программу
    main()

### Задание 2 итог:
- Исходный код программы на языке Python: выше.
- Краткое описание основных шагов и решений, принятых в процессе разработки: краткое описание принципов работы находится перед блоком с кодом + подробные комментарии `#` справа от строчек кода.
- Примеры визуализаций (при наличии): примеры спарсенных новостей и визуализаций, за две итерации запуска программы, прикреплю отдельным файлом. Или, если вы запустиили программу на своём пк, то вы найдёте файлы: `raw_news.json`, `processed_news.csv` и `daily_mentions`, `source_mentions` в созданных программой папках `data` и `plots`. (Например, `http://localhost:8888/lab/tree/plots/daily_mentions.png`)